POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name": "tuan le",
    "username": "Adagaki456",
    "password": "1234"
}

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "Adagaki456",
    "password": "1234"
}

###

GET http://127.0.0.1:8000/api/auth
Accept: application/json
Authorization: 6|ck8ykmVqXAS7a2CN2wJqgGnoT1MqzXmXbcNlj8Sh

###

GET http://127.0.0.1:8000/api/logout
Accept: application/json
Authorization: 6|ck8ykmVqXAS7a2CN2wJqgGnoT1MqzXmXbcNlj8Sh


###

GET http://127.0.0.1:8000/api/get-restaurants
Accept: application/json
Authorization: 1|BT4nRrBlh72uuRD29My8NeOXHpHOV6bLHEfb0xU9

###
GET http://127.0.0.1:8000/api/get-restaurant
Accept: application/json
Authorization: 1|BT4nRrBlh72uuRD29My8NeOXHpHOV6bLHEfb0xU9
###

POST http://127.0.0.1:8000/api/add-restaurant
Content-Type: : application/json
Authorization: 14|zlt4aNQ6O74fAyzRVTxvl2pPo7bA2fztMPJEr5L4

{
    "name": "banh trang tron 2",
    "description": "ngon lam!",
    "address": "gan truong C3",
    "image": "image"
}

###

PUT http://127.0.0.1:8000/api/update-restaurant/1
Content-Type: application/json

{
    "name": "Com rang dua bo",
    "description": "Ngoc ru di an thay binh thuong",
    "address": "Truoc cong tran dai nghia Bach Khoa",
    "image": "anh minh hoa"
}

###
DELETE http://127.0.0.1:8000/api/delete-restaurant/2

###

GET http://127.0.0.1:8000/api/user